### PR TITLE
Add Steven Murawski (smurawski) as Windows Maintainer

### PR DESCRIPTION
**Pull request by smurawski**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
w00t! :+1:

**Comment by nathenharvey** [comment]
seems obvious to me that this should get all the :+1:s required.

Paging other Chef core maintainers to weigh in.  /cc @jonlives @jaymzh @tyler-ball @danielsdeleo @mcquin

**Comment by danielsdeleo** [comment]
:+1:

**Comment by jonlives** [comment]
:+1:

**Comment by mcquin** [comment]
+1

**Comment by tyler-ball** [comment]
:shipit: :cake:

**Comment by jonlives** [comment]
@adamhjk just need deciderating now!

**Comment by adamhjk** [comment]
My only question there is who is the LT for Windows going to be. I am, of course, stoked to have @smurawski :)

**Comment by smurawski** [comment]
@adamhjk I thought I should spend a bit more time immersing myself in the project and community before I suggest myself for the lieutenant position for the platform.

**Pull request merged**
