### PR TITLE
Allow knife to install cookbooks with metadata.json

### PR DESCRIPTION
**Pull request by sethvargo**
Previously `knife cookbook site install` would only install cookbooks that have a metadata.rb. This has a number of problems, mainly that compiled metadata is supported elsewhere in Chef.

This commit adds support for parsing the metadata.json, even though the metadata.rb is still preferred (since that's what the rest of Chef does).

Refs: https://github.com/sethvargo/stove/pull/59

/cc @nathenharvey

### CODE REVIEW

**Comment by martinb3** [comment]
:+1: I've got some users of my cookbooks reporting this bug as well.

**Comment by sethvargo** [comment]
@jdmundrawala I believe this can be closed? Or did we only backport the change and not merge to master?

**Comment by jdmundrawala** [comment]
@sethvargo It was released in a version of 12. I will close this once 11.18.0 goes out the door.

**Comment by jdmundrawala** [comment]
12.0.2 is what @btm said above

**Comment by sethvargo** [comment]
kk. I just wanted to make sure you weren't waiting on anything from me :smile:

**Comment by sethvargo** [comment]
@nathenharvey I think there's an open ticket on a cookbook (maybe openssl) that refers to this issue that can probably be closed too.

**Comment by jdmundrawala** [comment]
Released in 11.18.0

**Pull request closed without merging**
